use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :chatbot, ChatbotWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "sheltered-caverns-23304.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

config :chatbot, ChatbotWeb.ChatbotController,
  page_access_token: System.get_env("PAGE_ACCESS_TOKEN"),
  verify_token: "ba212eeb69a50f8c4e3533992e98a125"


config :chatbot, GraphClient,
  graph_url: "https://graph.facebook.com",
  page_id: System.get_env("PAGE_ID"),
  app_id: System.get_env("APP_ID"),
  page_access_token: System.get_env("PAGE_ACCESS_TOKEN"),
  app_secret: System.get_env("APP_SECRET")

config :chatbot, IbmClient,
  url: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com/instances/c7482003-969f-44b6-aa06-9b80ee40b86d/v1",
  version: "2019-07-02",
  api_key: System.get_env("IBM_API_KEY")

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :chatbot, ChatbotWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :chatbot, ChatbotWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
